### ISSUE TITLE
Music Time for Spotify Extension host terminated unexpectedly in apple silicon on stable version.

### ISSUE THREAD

**Issue by premkumar5012002** [swdotcom/swdc-vscode-musictime#54]
**Describe the bug**
```paste below
Extension host terminated unexpectedly
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

**Expected behavior**
```paste below

```

**ACTUAL RESULTS**

```paste below

```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Plugin version [e.g. Code Time v1.2.1]

**Additional context**
```paste below

```
<img width="1440" alt="Screenshot 2021-03-07 at 11 53 31 AM" src="https://user-images.githubusercontent.com/60777829/110231125-c338a700-7f3b-11eb-8adc-c67c160fa273.png">

**Comment by xavluiz** [comment]
Thank you for the issue report and the error details. This helps and we'll look at this right away.
Regards.

**Comment by xavluiz** [comment]
Hi @premkumar5012002. I was able to reproduce a similar error and found that it may be due to opening a non-git based project. I've deployed a new version, v2.1.9, to fix that issue but let us know if there's any other issues, thank you.

**Comment by premkumar5012002** [comment]
Still facing the same bug after installing v2.1.9 on my apple silicon m1 version of macbook in vs code stable version.

**Comment by xavluiz** [comment]
Ok, my apologies about the previous update not resolving the issue. I'll work with a resource to see what may be happing today, thank you.

**Comment by premkumar5012002** [comment]
music for spotify extension working properly without issue.

**Comment by premkumar5012002** [comment]
again facing the same issue after the update.

**Comment by xavluiz** [comment]
Ok, thanks for the update. We'll look into this.

**Comment by xavluiz** [comment]
Hi @premkumar5012002 , do you have "git" installed? The errors seem related to git not being installed. It's ok if it's not installed, we need to make sure the plugin works without that but this information will help us reproduce the error, thank you.

**Comment by premkumar5012002** [comment]
Yes I have git. For git initiated it works fine but not for non-git projects.

**Comment by xavluiz** [comment]
I see, that helps. We should have a fix for this very soon based on that information, thank you.

**Comment by xavluiz** [comment]
We've reproduced the issue when opening vscode with a non-git based project and fixed the underlying problem. The fix is now in v2.1.13. Please let us know if there's any other issues. Thank you.
